# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XingSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Search term')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('status', models.SmallIntegerField(choices=[(1, 'Search in process'), (2, 'Search is finished'), (3, 'Search has errors'), (4, 'Xing user is not logged in'), (5, 'Xing user has been authenticated'), (6, 'Xing asks verification code'), (7, 'Xing verification code is not valid'), (8, 'No Xing user was added to the db'), (9, 'Xing asks premium'), (10, 'Connection refused'), (11, 'Task has been restarted')], default=1, verbose_name='Status of search')),
                ('search_type', models.SmallIntegerField(choices=[(1, 'Search by company or company ID'), (2, 'Search by Geo')], default=1, verbose_name='Search type')),
                ('search_geo', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Search geo location')),
                ('last_scraped_page', models.IntegerField(blank=True, default=None, null=True, verbose_name='Last scraped employees page')),
            ],
        ),
        migrations.CreateModel(
            name='XingSearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Last name')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Title')),
                ('current_company', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Current company')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Location')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xingapp.XingSearch', verbose_name='Xing Search instance')),
            ],
        ),
        migrations.CreateModel(
            name='XingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, verbose_name='Xing email')),
                ('password', models.CharField(max_length=120, verbose_name='Xing password')),
            ],
        ),
    ]
