# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xingsearchresult',
            name='title',
        ),
        migrations.AddField(
            model_name='xingsearchresult',
            name='current_position',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Current position'),
        ),
        migrations.AddField(
            model_name='xingsearchresult',
            name='employee_link',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Employee link'),
        ),
    ]
